# Web-Port
server.port=8080

# H2 Datenbank Einstellungen
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# SQL Initialisierung aktivieren
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create-drop

# H2 Konsole (zum Reinschauen in die Tabellen)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console